branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - rvm install 2.1.5
  - npm install -g grunt-cli
install:
  - gem install compass
  - pip install --user fpdf
  - npm install
  - npm run bower
script:
  - ./publish-to-gh-pages.sh
after_success:
env:
  global:
    - GitHub_REF: github.com/trista099/resume.git
